// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
)

const counts = `-- name: Counts :one
SELECT
    (SELECT COUNT(*) FROM customers)                          AS customers,
    (SELECT COUNT(*) FROM vehicles)                           AS vehicles,
    (SELECT COUNT(*) FROM parts)                              AS parts,
    (SELECT COUNT(*) FROM parts WHERE quantity_on_hand = 0)   AS out_of_stock
`

type CountsRow struct {
	Customers  int64
	Vehicles   int64
	Parts      int64
	OutOfStock int64
}

// One round trip for the home page rather than four.
func (q *Queries) Counts(ctx context.Context) (CountsRow, error) {
	row := q.db.QueryRow(ctx, counts)
	var i CountsRow
	err := row.Scan(
		&i.Customers,
		&i.Vehicles,
		&i.Parts,
		&i.OutOfStock,
	)
	return i, err
}

const listPartsOutOfStock = `-- name: ListPartsOutOfStock :many
SELECT id, reference, name, price_millimes, quantity_on_hand, created_at FROM parts
WHERE quantity_on_hand = 0
ORDER BY name
LIMIT 5
`

func (q *Queries) ListPartsOutOfStock(ctx context.Context) ([]Part, error) {
	rows, err := q.db.Query(ctx, listPartsOutOfStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Name,
			&i.PriceMillimes,
			&i.QuantityOnHand,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCustomers = `-- name: ListRecentCustomers :many
SELECT id, name, phone, city, created_at FROM customers
ORDER BY created_at DESC, id DESC
LIMIT 5
`

func (q *Queries) ListRecentCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listRecentCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
