// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :one
INSERT INTO service_jobs (vehicle_id, description, status, labour_millimes)
VALUES ($1, $2, $3, $4)
RETURNING id, vehicle_id, status, description, labour_millimes, opened_at
`

type CreateJobParams struct {
	VehicleID      int64
	Description    string
	Status         string
	LabourMillimes int32
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.VehicleID,
		arg.Description,
		arg.Status,
		arg.LabourMillimes,
	)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Status,
		&i.Description,
		&i.LabourMillimes,
		&i.OpenedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM service_jobs
WHERE id = $1
`

// No route reaches this: a job that is not happening is cancelled, not erased.
// It exists so tests and the seeder can leave the database as they found it.
func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, vehicle_id, status, description, labour_millimes, opened_at FROM service_jobs
WHERE id = $1
`

// No join: the handler already loads the vehicle and its owner through the store
// methods that exist, and three lookups by primary key are cheaper to read than a
// fourth generated row type.
func (q *Queries) GetJob(ctx context.Context, id int64) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Status,
		&i.Description,
		&i.LabourMillimes,
		&i.OpenedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT
    j.id,
    j.status,
    j.description,
    j.labour_millimes,
    j.opened_at,
    v.id   AS vehicle_id,
    v.plate,
    v.make,
    v.model,
    c.id   AS customer_id,
    c.name AS customer_name
FROM service_jobs j
    JOIN vehicles v ON v.id = j.vehicle_id
    JOIN customers c ON c.id = v.customer_id
ORDER BY j.opened_at DESC, j.id DESC
`

type ListJobsRow struct {
	ID             int64
	Status         string
	Description    string
	LabourMillimes int32
	OpenedAt       time.Time
	VehicleID      int64
	Plate          string
	Make           string
	Model          string
	CustomerID     int64
	CustomerName   string
}

// The list page shows which car and whose it is, so the join happens here rather
// than as one extra query per row on the page.
func (q *Queries) ListJobs(ctx context.Context) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Description,
			&i.LabourMillimes,
			&i.OpenedAt,
			&i.VehicleID,
			&i.Plate,
			&i.Make,
			&i.Model,
			&i.CustomerID,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByCustomer = `-- name: ListJobsByCustomer :many
SELECT
    j.id,
    j.status,
    j.description,
    j.labour_millimes,
    j.opened_at,
    v.id AS vehicle_id,
    v.plate
FROM service_jobs j
    JOIN vehicles v ON v.id = j.vehicle_id
WHERE v.customer_id = $1
ORDER BY j.opened_at DESC, j.id DESC
`

type ListJobsByCustomerRow struct {
	ID             int64
	Status         string
	Description    string
	LabourMillimes int32
	OpenedAt       time.Time
	VehicleID      int64
	Plate          string
}

// A customer's jobs across all of their vehicles, for their page. The plate comes
// along so each row says which car it was.
func (q *Queries) ListJobsByCustomer(ctx context.Context, customerID int64) ([]ListJobsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listJobsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByCustomerRow
	for rows.Next() {
		var i ListJobsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Description,
			&i.LabourMillimes,
			&i.OpenedAt,
			&i.VehicleID,
			&i.Plate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
