// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Customer struct {
	ID        int64
	Name      string
	Phone     string
	City      string
	CreatedAt time.Time
}
