// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Customer struct {
	ID        int64
	Name      string
	Phone     string
	City      string
	CreatedAt time.Time
}

type Part struct {
	ID             int64
	Reference      string
	Name           string
	PriceMillimes  int32
	QuantityOnHand int32
	CreatedAt      time.Time
}

type ServiceJob struct {
	ID             int64
	VehicleID      int64
	Status         string
	Description    string
	LabourMillimes int32
	OpenedAt       time.Time
}

type Vehicle struct {
	ID         int64
	CustomerID int64
	Plate      string
	Make       string
	Model      string
	Year       int32
	CreatedAt  time.Time
}
