// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parts.sql

package db

import (
	"context"
)

const createPart = `-- name: CreatePart :one
INSERT INTO parts (reference, name, price_millimes, quantity_on_hand)
VALUES ($1, $2, $3, $4)
RETURNING id, reference, name, price_millimes, quantity_on_hand, created_at
`

type CreatePartParams struct {
	Reference      string
	Name           string
	PriceMillimes  int32
	QuantityOnHand int32
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, createPart,
		arg.Reference,
		arg.Name,
		arg.PriceMillimes,
		arg.QuantityOnHand,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Name,
		&i.PriceMillimes,
		&i.QuantityOnHand,
		&i.CreatedAt,
	)
	return i, err
}

const deletePart = `-- name: DeletePart :exec
DELETE FROM parts
WHERE id = $1
`

func (q *Queries) DeletePart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePart, id)
	return err
}

const getPart = `-- name: GetPart :one
SELECT id, reference, name, price_millimes, quantity_on_hand, created_at FROM parts
WHERE id = $1
`

func (q *Queries) GetPart(ctx context.Context, id int64) (Part, error) {
	row := q.db.QueryRow(ctx, getPart, id)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Name,
		&i.PriceMillimes,
		&i.QuantityOnHand,
		&i.CreatedAt,
	)
	return i, err
}

const listParts = `-- name: ListParts :many
SELECT id, reference, name, price_millimes, quantity_on_hand, created_at FROM parts
ORDER BY name, reference
`

func (q *Queries) ListParts(ctx context.Context) ([]Part, error) {
	rows, err := q.db.Query(ctx, listParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Name,
			&i.PriceMillimes,
			&i.QuantityOnHand,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePart = `-- name: UpdatePart :one
UPDATE parts
SET reference = $2, name = $3, price_millimes = $4, quantity_on_hand = $5
WHERE id = $1
RETURNING id, reference, name, price_millimes, quantity_on_hand, created_at
`

type UpdatePartParams struct {
	ID             int64
	Reference      string
	Name           string
	PriceMillimes  int32
	QuantityOnHand int32
}

func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, updatePart,
		arg.ID,
		arg.Reference,
		arg.Name,
		arg.PriceMillimes,
		arg.QuantityOnHand,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Name,
		&i.PriceMillimes,
		&i.QuantityOnHand,
		&i.CreatedAt,
	)
	return i, err
}
