// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package db

import (
	"context"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (customer_id, plate, make, model, year)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, plate, make, model, year, created_at
`

type CreateVehicleParams struct {
	CustomerID int64
	Plate      string
	Make       string
	Model      string
	Year       int32
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.CustomerID,
		arg.Plate,
		arg.Make,
		arg.Model,
		arg.Year,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Plate,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, customer_id, plate, make, model, year, created_at FROM vehicles
WHERE id = $1
`

func (q *Queries) GetVehicle(ctx context.Context, id int64) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Plate,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const listVehiclesByCustomer = `-- name: ListVehiclesByCustomer :many
SELECT id, customer_id, plate, make, model, year, created_at FROM vehicles
WHERE customer_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListVehiclesByCustomer(ctx context.Context, customerID int64) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Plate,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET plate = $2, make = $3, model = $4, year = $5
WHERE id = $1
RETURNING id, customer_id, plate, make, model, year, created_at
`

type UpdateVehicleParams struct {
	ID    int64
	Plate string
	Make  string
	Model string
	Year  int32
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.Plate,
		arg.Make,
		arg.Model,
		arg.Year,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Plate,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}
